# processors provide the raw information of documents
# the advanced information is generated by unit_generator
from processors.Doc_processor import Doc_processor    # cls
from processors.processor_plugins import Processor_plugin_ch, Processor_plugin_en    # modules